name: da-backend
services:
  application:
    container_name: SpringBoot
    build:
      dockerfile: ./Dockerfile
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}:${DOCKERHUB_TAG}
    ports:
      - "${APPLICATION_PORT}:8080"
    environment:
      - AD_USER=${AD_USER}
      - AD_PASSWORD=${AD_PASSWORD}
      - APPLICATION_ADMINS=${APPLICATION_ADMINS}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    depends_on:
      database:
        condition: service_started
    networks:
      - DA-Backend
    links:
      - database

  database:
    container_name: MariaDB
    image: mariadb:latest
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    volumes:
      - database:/var/lib/mysql
    networks:
      - DA-Backend

networks:
  DA-Backend:
    driver: bridge

volumes:
  database: