services:
  application:
    container_name: DA-Backend
    build:
      dockerfile: ./Dockerfile
    image: mpointner/da-backend:latest
    ports:
      - "8080:8080"
    environment:
      AD_USER: ${AD_USER}
      AD_PASSWORD: ${AD_PASSWORD}
      ADMINS: ${ADMINS}
    depends_on:
      - database
  database:
    container_name: DA-MariaDB
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpw
      MYSQL_DATABASE: dev
    volumes:
      - database:/var/lib/mysql
volumes:
  database: