name: da-backend
services:
  application:
    container_name: SpringBoot
    build:
      dockerfile: ./Dockerfile
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}:latest
    ports:
      - "8080:8080"
    environment:
      - AD_USER=${AD_USER}
      - AD_PASSWORD=${AD_PASSWORD}
      - ADMINS=${ADMINS}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    depends_on:
      database:
        condition: service_started
    networks:
      - DA-Backend

  database:
    container_name: MariaDB
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - database:/var/lib/mysql
    networks:
      - DA-Backend

networks:
  DA-Backend:
    driver: bridge

volumes:
  database: